In [0]:
import numpy as np
import pandas as pd
import seaborn as sns

from sklearn.ensemble import RandomForestRegressor

df2 = pd.read_csv('https://docs.google.com/spreadsheets/d/e/2PACX-1vRrC0pd9TVoYAjBYG2OrrC0yO7VsOb-kvq3w0A8sN02JxbWw0PtEgWEnZckAWZqItE3fl51MzxsQpkU/pub?gid=273957857&single=true&output=csv')
#normalize to log norm
df2.homicides = np.log(df2.homicides)
df2.head()

   Year       State  ...  AlcoholConsumptionPerCapita  PropOfMales
0  2014     Alabama  ...                         2.00     0.495271
1  2014      Alaska  ...                         2.79     0.535216
2  2014     Arizona  ...                         2.38     0.512376
3  2014    Arkansas  ...                         1.79     0.502776
4  2014  California  ...                         2.32     0.509981

[5 rows x 44 columns]

In [0]:
#normalize to log norm
df2.homicides = np.log(df2.homicides)
df2.head()

   Year       State  ...  AlcoholConsumptionPerCapita  PropOfMales
0  2014     Alabama  ...                         2.00     0.495271
1  2014      Alaska  ...                         2.79     0.535216
2  2014     Arizona  ...                         2.38     0.512376
3  2014    Arkansas  ...                         1.79     0.502776
4  2014  California  ...                         2.32     0.509981

[5 rows x 44 columns]

# RF from ALL MODELS Colab file

In [0]:
def fit_and_score_model(mdl, x_train, x_test, y_train, y_test, random_state=0):
    """
    This function will fit and score the input mdl to the x_train and y_train 
    data, and score the mdl on y_train and y_test. To ensure results are 
    reproducible we can also set a random state.
    """
  
    # Fit an arbitrary model
    mdl.fit(x_train, y_train)
    
    # Calculate the score of the model on training and testing data
    train_score = mdl.score(x_train, y_train)
    test_score = mdl.score(x_test, y_test)
  
    # Print scores to terminal
    print('the accuracy on the: \n\t training data is {}'.format(round(train_score,3)))
    print('\t testing data is {}'.format(round(test_score, 3)))
    
    return train_score, test_score

In [0]:
  def scoreData(df,mdl,dfName):
  #split training set
    df_train = df[df.Year<2018]
    df_test = df[df.Year==2018]

  #partition features
    X_train = df_train.drop(columns=['homicides', 'State', 'Year', 'MagExists', 'HRExists', 'BKExists', 'universalpermit','gunshowh', 'universalpermith', 'mentalhealth', 'backgroundpurge', 'universalh', 'gunshow', 'homicidespercap'])
    y_train = df_train.homicides

    # Partition the testing data into features and target
    X_test = df_test.drop(columns=['homicides', 'State', 'Year', 'MagExists', 'HRExists', 'BKExists', 'universalpermit','gunshowh', 'universalpermith', 'mentalhealth', 'backgroundpurge', 'universalh', 'gunshow',  'homicidespercap'])
    y_test = df_test.homicides

    train_score = mdl.score(X_train, y_train)
    test_score = mdl.score(X_test, y_test)

    print('{}: The train score is {} and the test score is {}'.format(dfName,train_score, test_score))
    return train_score, test_score

In [0]:
  #split training set
    df_train = df2[df2.Year<2018]
    df_test = df2[df2.Year==2018]

  #partition features
    X_train = df_train.drop(columns=['homicides', 'State', 'Year', 'MagExists', 'HRExists', 'BKExists', 'universalpermit','gunshowh', 'universalpermith', 'mentalhealth', 'backgroundpurge', 'universalh', 'gunshow', 'homicidespercap'])
    y_train = df_train.homicides

    # Partition the testing data into features and target
    X_test = df_test.drop(columns=['homicides', 'State', 'Year', 'MagExists', 'HRExists', 'universalpermit', 'BKExists','gunshowh', 'universalpermith', 'mentalhealth', 'backgroundpurge', 'universalh', 'gunshow', 'homicidespercap'])
    y_test = df_test.homicides

    # Initialize the model
    rf_baseline_model = RandomForestRegressor(
        random_state = 0, 
        max_depth = None,
        n_estimators = 30, max_features = 0.2
    )

In [0]:
# Initialize the model
    rf_baseline_model = RandomForestRegressor()
    
    # Fit and train model
    train_score, test_score = fit_and_score_model(rf_baseline_model, X_train, X_test, y_train, y_test)
    #scoreData(df2, rf_baseline_model, "hi")

the accuracy on the:
	 training data is 0.998
	 testing data is 0.979

/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)

In [0]:
from sklearn.ensemble import RandomForestRegressor
# Write your code here. 

# -------------------

depths = [None, 2, 3, 4, 5, 6, 7]
accuracy = pd.Series(index=depths)

for max_depth in depths:

    # Initialize the model
    rf_baseline_model = RandomForestRegressor(
        random_state = 0, 
        max_depth = max_depth,
        n_estimators = 30, max_features = 0.2
    )
    
    # Fit and train model
    print('For {} max_depth '.format(max_depth), end='')
    train_score, test_score = fit_and_score_model(rf_baseline_model, X_train, X_test, y_train, y_test)
    
    # Save model performance to dataframe
    #cheat_scores.loc[max_depth] = test_score
    
#print('\n***Best model has a score of {:.3f} with a max_depth of {}***'.format(cheat_scores.max(), cheat_scores.idxmax()))

# -------------------

For None max_depth the accuracy on the:
	 training data is 0.997
	 testing data is 0.985
For 2 max_depth the accuracy on the:
	 training data is 0.717
	 testing data is 0.705
For 3 max_depth the accuracy on the:
	 training data is 0.866
	 testing data is 0.86
For 4 max_depth the accuracy on the:
	 training data is 0.941
	 testing data is 0.932
For 5 max_depth the accuracy on the:
	 training data is 0.969
	 testing data is 0.959
For 6 max_depth the accuracy on the:
	 training data is 0.985
	 testing data is 0.972
For 7 max_depth the accuracy on the:
	 training data is 0.99
	 testing data is 0.98

# Gridsearch

In [0]:
from sklearn.model_selection import GridSearchCV

params_to_search = {
    'criterion': ['mse', 'mae'],
    'min_samples_leaf': [1, 2, 5, 10, 20],
    'max_features': ['auto', 'log2', None, 0.2, 0.5],
    'max_depth':[2,3,4,5,6,7, None]
}

mdl = RandomForestRegressor(random_state=1, n_estimators = 100, n_jobs=-1)
optimized_dt = GridSearchCV(mdl, params_to_search, scoring = 'r2',refit=False, cv=5)
optimized_dt

GridSearchCV(cv=5, error_score='raise-deprecating',
             estimator=RandomForestRegressor(bootstrap=True, criterion='mse',
                                             max_depth=None,
                                             max_features='auto',
                                             max_leaf_nodes=None,
                                             min_impurity_decrease=0.0,
                                             min_impurity_split=None,
                                             min_samples_leaf=1,
                                             min_samples_split=2,
                                             min_weight_fraction_leaf=0.0,
                                             n_estimators=100, n_jobs=-1,
                                             oob_score=False, random_state=1,
                                             verbose=0, warm_start=False),
             iid='warn', n_jobs=None,
             param_grid={'criterion': ['mse', 'mae'],
                         'max_depth': [2, 3, 4, 5, 6, 7, None],
                         'max_features': ['auto', 'log2', None, 0.2, 0.5],
                         'min_samples_leaf': [1, 2, 5, 10, 20]},
             pre_dispatch='2*n_jobs', refit=False, return_train_score=False,
             scoring='r2', verbose=0)

In [0]:
 # Fit and train model after gridsearch (grid search recommended everything be default)
    train_score, test_score = fit_and_score_model(mdl, X_train, X_test, y_train, y_test)

the accuracy on the:
	 training data is 0.997
	 testing data is 0.979

In [0]:
features = pd.Series(X_test.columns)
features

0                       universal
1                   ammbackground
2                   threedaylimit
3                     statechecks
4                    statechecksh
5                          felony
6                   invcommitment
7                   invoutpatient
8                          danger
9                 drugmisdemeanor
10                   alctreatment
11                     alcoholism
12                 relinquishment
13                        violent
14                       violenth
15                 violentpartial
16                       magazine
17                  tenroundlimit
18               magazinepreowned
19                          White
20                          Black
21                         Native
22                          Asian
23                       Islander
24                     Num_police
25                    Popden_2010
26                     Population
27                      FLLPerCap
28    AlcoholConsumptionPerCapita
29                    PropOfMales
dtype: object

In [0]:
feature_sig = pd.Series(mdl.feature_importances_)
feature_sig.sort_values(ascending = False)

26    0.902353
24    0.061325
23    0.007826
29    0.006436
27    0.004337
20    0.002945
28    0.002494
25    0.002246
19    0.002144
22    0.001908
21    0.001880
6     0.000716
8     0.000651
3     0.000340
2     0.000306
15    0.000280
12    0.000251
9     0.000251
4     0.000242
7     0.000214
5     0.000195
1     0.000155
17    0.000096
0     0.000094
10    0.000087
14    0.000072
11    0.000066
16    0.000061
18    0.000020
13    0.000008
dtype: float64

In [0]:
mdl.predict(X_test)

array([8.25410978, 6.5635117 , 8.65481037, 7.80698936, 9.85521056,
       8.45610621, 7.73005822, 6.57903753, 9.6895943 , 8.75481072,
       8.96654556, 8.49794946, 7.64919844, 8.33858983, 8.30728624,
       7.00705328, 8.48784543, 8.43322151, 8.85661735, 8.20363743,
       7.75297169, 8.55006095, 7.68317451, 8.49962689, 7.68722215,
       9.12739629, 8.84086788, 9.14494361, 8.17897856, 8.0048912 ,
       9.26061629, 8.33997354, 8.63950688, 9.66970278, 7.63380607,
       8.5363124 , 8.48061022, 7.67111117, 8.42241689])

In [0]:
BeforeERLPredict2018 = pd.Series(mdl.predict(X_test))
BeforeERLPredict2018

0     8.254110
1     6.563512
2     8.654810
3     7.806989
4     9.855211
5     8.456106
6     7.730058
7     6.579038
8     9.689594
9     8.754811
10    8.966546
11    8.497949
12    7.649198
13    8.338590
14    8.307286
15    7.007053
16    8.487845
17    8.433222
18    8.856617
19    8.203637
20    7.752972
21    8.550061
22    7.683175
23    8.499627
24    7.687222
25    9.127396
26    8.840868
27    9.144944
28    8.178979
29    8.004891
30    9.260616
31    8.339974
32    8.639507
33    9.669703
34    7.633806
35    8.536312
36    8.480610
37    7.671111
38    8.422417
dtype: float64

# Extreme Risk Law

In [0]:
#df2 = pd.read_csv('https://docs.google.com/spreadsheets/d/e/2PACX-1vRrC0pd9TVoYAjBYG2OrrC0yO7VsOb-kvq3w0A8sN02JxbWw0PtEgWEnZckAWZqItE3fl51MzxsQpkU/pub?gid=273957857&single=true&output=csv')

dfERL = pd.read_csv('https://docs.google.com/spreadsheets/d/e/2PACX-1vRAPDWT5Z1W_n4CE4wyGc-D6iQarEO7mDByT0gciPNnDKpraT6dmoRR88_zvIsCjc5vSCSttnlEnl1q/pub?gid=0&single=true&output=csv')
dfERL.Homicides = np.log(dfERL.Homicides)
dfERL.head()

   Year       State  ...  AlcoholConsumptionPerCapita  PropOfMales
0  2018     Alabama  ...                         2.00     0.494460
1  2018      Alaska  ...                         2.87     0.534529
2  2018     Arizona  ...                         2.30     0.513779
3  2018    Arkansas  ...                         1.82     0.503630
4  2018  California  ...                         2.31     0.511435

[5 rows x 43 columns]

In [0]:
#normalize to log norm
dfERL.Homicides = np.log(dfERL.Homicides)
dfERL.head()

   Year       State  ...  AlcoholConsumptionPerCapita  PropOfMales
0  2018     Alabama  ...                         2.00     0.494460
1  2018      Alaska  ...                         2.87     0.534529
2  2018     Arizona  ...                         2.30     0.513779
3  2018    Arkansas  ...                         1.82     0.503630
4  2018  California  ...                         2.31     0.511435

[5 rows x 43 columns]

In [0]:
  #split training set
    df_test1 = dfERL[dfERL.Year==2018]

   # Partition the testing data into features and target
    X_test1 = df_test1.drop(columns=['Homicides', 'State', 'Year', 'MagExists', 'HRExists', 'universalpermit', 'BKExists','gunshowh', 'universalpermith', 'mentalhealth', 'backgroundpurge', 'universalh', 'gunshow'])
    y_test1 = df_test1.Homicides

In [0]:
mdl2 = RandomForestRegressor(random_state=1, n_estimators = 100, n_jobs=-1)
optimized_dt2 = GridSearchCV(mdl2, params_to_search, scoring = 'r2',refit=False, cv=5)
optimized_dt2

GridSearchCV(cv=5, error_score='raise-deprecating',
             estimator=RandomForestRegressor(bootstrap=True, criterion='mse',
                                             max_depth=None,
                                             max_features='auto',
                                             max_leaf_nodes=None,
                                             min_impurity_decrease=0.0,
                                             min_impurity_split=None,
                                             min_samples_leaf=1,
                                             min_samples_split=2,
                                             min_weight_fraction_leaf=0.0,
                                             n_estimators=100, n_jobs=-1,
                                             oob_score=False, random_state=1,
                                             verbose=0, warm_start=False),
             iid='warn', n_jobs=None,
             param_grid={'criterion': ['mse', 'mae'],
                         'max_depth': [2, 3, 4, 5, 6, 7, None],
                         'max_features': ['auto', 'log2', None, 0.2, 0.5],
                         'min_samples_leaf': [1, 2, 5, 10, 20]},
             pre_dispatch='2*n_jobs', refit=False, return_train_score=False,
             scoring='r2', verbose=0)

In [0]:
# Fit and train model
    train_score, test_score = fit_and_score_model(mdl2, X_train, X_test1, y_train, y_test1)

the accuracy on the:
	 training data is 0.997
	 testing data is -4791.312

In [0]:
mdl2.predict(X_test1)

array([8.25410978, 6.57383096, 8.65481037, 7.80698936, 9.85521056,
       8.45554687, 7.73005822, 6.57903753, 9.69604132, 8.79801079,
       8.96654556, 8.5034518 , 7.64919844, 8.33723082, 8.30536582,
       7.00705328, 8.48784543, 8.43322151, 8.89061021, 8.20363743,
       7.7524411 , 8.55108212, 7.68317451, 8.49962689, 7.68790998,
       9.12739629, 8.86875915, 9.14494361, 8.17442508, 8.0048912 ,
       9.26061629, 8.33997354, 8.63950688, 9.67435432, 7.63380607,
       8.5363124 , 8.48061022, 7.67111117, 8.42241689])

In [0]:
ERLResults2018 = pd.Series(mdl2.predict(X_test1))
ERLResults2018

0     8.254110
1     6.573831
2     8.654810
3     7.806989
4     9.855211
5     8.455547
6     7.730058
7     6.579038
8     9.696041
9     8.798011
10    8.966546
11    8.503452
12    7.649198
13    8.337231
14    8.305366
15    7.007053
16    8.487845
17    8.433222
18    8.890610
19    8.203637
20    7.752441
21    8.551082
22    7.683175
23    8.499627
24    7.687910
25    9.127396
26    8.868759
27    9.144944
28    8.174425
29    8.004891
30    9.260616
31    8.339974
32    8.639507
33    9.674354
34    7.633806
35    8.536312
36    8.480610
37    7.671111
38    8.422417
dtype: float64

# ammbackground

In [0]:
dfamm = pd.read_csv('https://docs.google.com/spreadsheets/d/e/2PACX-1vRAPDWT5Z1W_n4CE4wyGc-D6iQarEO7mDByT0gciPNnDKpraT6dmoRR88_zvIsCjc5vSCSttnlEnl1q/pub?gid=1034501585&single=true&output=csv')
dfamm.Homicides = np.log(dfamm.Homicides)
dfamm.head()

   Year       State  ...  AlcoholConsumptionPerCapita  PropOfMales
0  2018     Alabama  ...                         2.00     0.494460
1  2018      Alaska  ...                         2.87     0.534529
2  2018     Arizona  ...                         2.30     0.513779
3  2018    Arkansas  ...                         1.82     0.503630
4  2018  California  ...                         2.31     0.511435

[5 rows x 43 columns]

In [0]:
 #split training set
df_test2 = dfamm[dfamm.Year==2018]

   # Partition the testing data into features and target
X_test2 = df_test2.drop(columns=['Homicides', 'State', 'Year', 'MagExists', 'HRExists', 'universalpermit', 'BKExists','gunshowh', 'universalpermith', 'mentalhealth', 'backgroundpurge', 'universalh', 'gunshow'])
y_test2 = df_test2.Homicides

mdl3 = RandomForestRegressor(random_state=1, n_estimators = 100, n_jobs=-1)
optimized_dt2 = GridSearchCV(mdl3, params_to_search, scoring = 'r2',refit=False, cv=5)
optimized_dt2

# Fit and train model
train_score, test_score = fit_and_score_model(mdl3, X_train, X_test2, y_train, y_test2)

mdl3.predict(X_test2)
AMMResults2018 = pd.Series(mdl3.predict(X_test2))
AMMResults2018

the accuracy on the:
	 training data is 0.997
	 testing data is 0.978

0     8.254110
1     6.563512
2     8.654810
3     7.805943
4     9.855211
5     8.456106
6     7.730058
7     6.579038
8     9.689594
9     8.754811
10    8.966546
11    8.498531
12    7.649208
13    8.338590
14    8.307286
15    7.007053
16    8.487845
17    8.433222
18    8.855183
19    8.203637
20    7.752972
21    8.550067
22    7.683175
23    8.499627
24    7.687222
25    9.110534
26    8.840716
27    9.121862
28    8.178979
29    8.004891
30    9.236080
31    8.339974
32    8.639507
33    9.669703
34    7.633806
35    8.536312
36    8.480610
37    7.671111
38    8.422417
dtype: float64

# Three Day Limit

In [0]:
df3dl.head()

   Year       State  ...  AlcoholConsumptionPerCapita  PropOfMales
0  2018     Alabama  ...                         2.00     0.494460
1  2018      Alaska  ...                         2.87     0.534529
2  2018     Arizona  ...                         2.30     0.513779
3  2018    Arkansas  ...                         1.82     0.503630
4  2018  California  ...                         2.31     0.511435

[5 rows x 43 columns]

In [0]:
df3dl = pd.read_csv('https://docs.google.com/spreadsheets/d/e/2PACX-1vRAPDWT5Z1W_n4CE4wyGc-D6iQarEO7mDByT0gciPNnDKpraT6dmoRR88_zvIsCjc5vSCSttnlEnl1q/pub?gid=2068488533&single=true&output=csv')
df3dl.Homicides = np.log(df3dl.Homicides)
df3dl.head()

  #split training set
df_test3 = df3dl[df3dl.Year==2018]

   # Partition the testing data into features and target
X_test3 = df_test3.drop(columns=['Homicides', 'State', 'Year', 'MagExists', 'HRExists', 'universalpermit', 'BKExists','gunshowh', 'universalpermith', 'mentalhealth', 'backgroundpurge', 'universalh', 'gunshow'])
y_test3 = df_test3.Homicides

mdl4 = RandomForestRegressor(random_state=1, n_estimators = 100, n_jobs=-1)
optimized_dt3 = GridSearchCV(mdl4, params_to_search, scoring = 'r2',refit=False, cv=5)
optimized_dt3

# Fit and train model
train_score, test_score = fit_and_score_model(mdl4, X_train, X_test3, y_train, y_test3)

mdl4.predict(X_test3)
DLResults2018 = pd.Series(mdl4.predict(X_test3))
DLResults2018

the accuracy on the:
	 training data is 0.997
	 testing data is 0.978

0     8.254110
1     6.606616
2     8.626548
3     7.806989
4     9.855211
5     8.456480
6     7.730058
7     6.579038
8     9.691968
9     8.755864
10    8.966546
11    8.495978
12    7.649198
13    8.338590
14    8.307286
15    7.007053
16    8.487845
17    8.433222
18    8.858875
19    8.203637
20    7.752972
21    8.531899
22    7.683175
23    8.487367
24    7.687222
25    9.125953
26    8.840868
27    9.142620
28    8.178979
29    8.004891
30    9.260616
31    8.339974
32    8.618663
33    9.671151
34    7.633806
35    8.522856
36    8.480610
37    7.671111
38    8.422590
dtype: float64

# magazine

In [0]:
dfmaga.head()

   Year       State  ...  AlcoholConsumptionPerCapita  PropOfMales
0  2018     Alabama  ...                         2.00     0.494460
1  2018      Alaska  ...                         2.87     0.534529
2  2018     Arizona  ...                         2.30     0.513779
3  2018    Arkansas  ...                         1.82     0.503630
4  2018  California  ...                         2.31     0.511435

[5 rows x 43 columns]

In [0]:
dfmaga = pd.read_csv('https://docs.google.com/spreadsheets/d/e/2PACX-1vRAPDWT5Z1W_n4CE4wyGc-D6iQarEO7mDByT0gciPNnDKpraT6dmoRR88_zvIsCjc5vSCSttnlEnl1q/pub?gid=151533888&single=true&output=csv')
dfmaga.Homicides = np.log(dfmaga.Homicides)
dfmaga.head()

  #split training set
df_test4 = dfmaga[dfmaga.Year==2018]

   # Partition the testing data into features and target
X_test4 = df_test4.drop(columns=['Homicides', 'State', 'Year', 'MagExists', 'HRExists', 'universalpermit', 'BKExists','gunshowh', 'universalpermith', 'mentalhealth', 'backgroundpurge', 'universalh', 'gunshow'])
y_test4 = df_test4.Homicides

mdl5 = RandomForestRegressor(random_state=1, n_estimators = 100, n_jobs=-1)
optimized_dt4 = GridSearchCV(mdl5, params_to_search, scoring = 'r2',refit=False, cv=5)
optimized_dt4

# Fit and train model
train_score, test_score = fit_and_score_model(mdl5, X_train, X_test4, y_train, y_test4)

mdl5.predict(X_test4)
MagaResults2018 = pd.Series(mdl5.predict(X_test4))
MagaResults2018

the accuracy on the:
	 training data is 0.997
	 testing data is 0.979

0     8.253433
1     6.563512
2     8.654810
3     7.807008
4     9.855211
5     8.456106
6     7.730058
7     6.579038
8     9.697791
9     8.754811
10    8.970439
11    8.497949
12    7.649198
13    8.337236
14    8.307286
15    7.007053
16    8.487845
17    8.433222
18    8.856617
19    8.203637
20    7.752338
21    8.549837
22    7.683175
23    8.499627
24    7.687222
25    9.127396
26    8.840868
27    9.145785
28    8.178979
29    8.004891
30    9.261657
31    8.339974
32    8.639507
33    9.674929
34    7.633806
35    8.536312
36    8.480702
37    7.671111
38    8.423187
dtype: float64

# Violent Partial

In [0]:
dfvp.head()

   Year       State  ...  AlcoholConsumptionPerCapita  PropOfMales
0  2018     Alabama  ...                         2.00     0.494460
1  2018      Alaska  ...                         2.87     0.534529
2  2018     Arizona  ...                         2.30     0.513779
3  2018    Arkansas  ...                         1.82     0.503630
4  2018  California  ...                         2.31     0.511435

[5 rows x 43 columns]

In [0]:
dfvp = pd.read_csv('https://docs.google.com/spreadsheets/d/e/2PACX-1vRAPDWT5Z1W_n4CE4wyGc-D6iQarEO7mDByT0gciPNnDKpraT6dmoRR88_zvIsCjc5vSCSttnlEnl1q/pub?gid=1383089960&single=true&output=csv')
dfvp.Homicides = np.log(dfvp.Homicides)
dfvp.head()

  #split training set
df_test5 = dfvp[dfvp.Year==2018]

   # Partition the testing data into features and target
X_test5 = df_test5.drop(columns=['Homicides', 'State', 'Year', 'MagExists', 'HRExists', 'universalpermit', 'BKExists','gunshowh', 'universalpermith', 'mentalhealth', 'backgroundpurge', 'universalh', 'gunshow'])
y_test5 = df_test5.Homicides

mdl6 = RandomForestRegressor(random_state=1, n_estimators = 100, n_jobs=-1)
optimized_dt5 = GridSearchCV(mdl6, params_to_search, scoring = 'r2',refit=False, cv=5)
optimized_dt5

# Fit and train model
train_score, test_score = fit_and_score_model(mdl6, X_train, X_test5, y_train, y_test5)

mdl6.predict(X_test5)
VPResults2018 = pd.Series(mdl6.predict(X_test5))
VPResults2018

the accuracy on the:
	 training data is 0.997
	 testing data is 0.979

0     8.237140
1     6.570581
2     8.654810
3     7.806311
4     9.855211
5     8.453157
6     7.730058
7     6.579038
8     9.699618
9     8.757387
10    8.966546
11    8.499088
12    7.650561
13    8.319159
14    8.284536
15    7.007053
16    8.487845
17    8.433222
18    8.856617
19    8.203637
20    7.752972
21    8.550061
22    7.683175
23    8.499627
24    7.688552
25    9.127396
26    8.841851
27    9.146470
28    8.174781
29    8.004891
30    9.260616
31    8.314980
32    8.639507
33    9.677267
34    7.633669
35    8.536312
36    8.482928
37    7.671111
38    8.419578
dtype: float64

# universal

In [0]:
dfu = pd.read_csv('https://docs.google.com/spreadsheets/d/e/2PACX-1vRAPDWT5Z1W_n4CE4wyGc-D6iQarEO7mDByT0gciPNnDKpraT6dmoRR88_zvIsCjc5vSCSttnlEnl1q/pub?gid=1582703551&single=true&output=csv')
dfu.Homicides = np.log(dfu.Homicides)
dfu.head()

  #split training set
df_test6 = dfu[dfu.Year==2018]

   # Partition the testing data into features and target
X_test6 = df_test6.drop(columns=['Homicides', 'State', 'Year', 'MagExists', 'HRExists', 'universalpermit', 'BKExists','gunshowh', 'universalpermith', 'mentalhealth', 'backgroundpurge', 'universalh', 'gunshow'])
y_test6 = df_test6.Homicides

mdl7 = RandomForestRegressor(random_state=1, n_estimators = 100, n_jobs=-1)
optimized_dt6 = GridSearchCV(mdl7, params_to_search, scoring = 'r2',refit=False, cv=5)
optimized_dt6

# Fit and train model
train_score, test_score = fit_and_score_model(mdl7, X_train, X_test6, y_train, y_test6)

mdl7.predict(X_test6)
UResults2018 = pd.Series(mdl7.predict(X_test6))
UResults2018

the accuracy on the:
	 training data is 0.997
	 testing data is 0.979

0     8.254110
1     6.564121
2     8.654810
3     7.807107
4     9.855211
5     8.456106
6     7.730058
7     6.579038
8     9.690978
9     8.754811
10    8.966546
11    8.497224
12    7.659594
13    8.338636
14    8.307286
15    7.007053
16    8.487845
17    8.433245
18    8.856617
19    8.201662
20    7.752726
21    8.550061
22    7.683175
23    8.498742
24    7.694398
25    9.127396
26    8.840868
27    9.146113
28    8.176889
29    8.004891
30    9.260616
31    8.339974
32    8.639507
33    9.674018
34    7.643145
35    8.536312
36    8.480610
37    7.679279
38    8.422216
dtype: float64

# Background check

In [0]:
dfBG = pd.read_csv('https://docs.google.com/spreadsheets/d/e/2PACX-1vRrC0pd9TVoYAjBYG2OrrC0yO7VsOb-kvq3w0A8sN02JxbWw0PtEgWEnZckAWZqItE3fl51MzxsQpkU/pub?gid=1734342827&single=true&output=csv')
#normalize to log norm
dfBG.homicides = np.log(dfBG.homicides)
dfBG.head()

   Year       State  ...  AlcoholConsumptionPerCapita  PropOfMales
0  2014     Alabama  ...                         2.00     0.495271
1  2014      Alaska  ...                         2.79     0.535216
2  2014     Arizona  ...                         2.38     0.512376
3  2014    Arkansas  ...                         1.79     0.502776
4  2014  California  ...                         2.32     0.509981

[5 rows x 28 columns]

In [0]:
  #split training set
    df_train = dfBG[dfBG.Year<2018]
    df_test = dfBG[dfBG.Year==2018]

  #partition features
    X_train = df_train.drop(columns=['homicides', 'State', 'Year', 'BKExists', 'universalpermit', 'universalpermith', 'mentalhealth', 'backgroundpurge', 'universalh', 'gunshow', 'homicidespercap'])
    y_train = df_train.homicides

    # Partition the testing data into features and target
    X_test = df_test.drop(columns=['homicides', 'State', 'Year', 'BKExists', 'universalpermit', 'universalpermith', 'mentalhealth', 'backgroundpurge', 'universalh', 'gunshow', 'homicidespercap'])
    y_test = df_test.homicides

    # Initialize the model
    mdlbg = RandomForestRegressor()
    
    # Fit and train model
    train_score, test_score = fit_and_score_model(mdlbg, X_train, X_test, y_train, y_test)

the accuracy on the:
	 training data is 0.996
	 testing data is 0.974

/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)

# High-Risk

In [0]:
dfHR = pd.read_csv('https://docs.google.com/spreadsheets/d/e/2PACX-1vRrC0pd9TVoYAjBYG2OrrC0yO7VsOb-kvq3w0A8sN02JxbWw0PtEgWEnZckAWZqItE3fl51MzxsQpkU/pub?gid=903831907&single=true&output=csv')
#normalize to log norm
dfHR.homicides = np.log(dfHR.homicides)
dfHR.head()

   Year       State  ...  AlcoholConsumptionPerCapita  PropOfMales
0  2014     Alabama  ...                         2.00     0.495271
1  2014      Alaska  ...                         2.79     0.535216
2  2014     Arizona  ...                         2.38     0.512376
3  2014    Arkansas  ...                         1.79     0.502776
4  2014  California  ...                         2.32     0.509981

[5 rows x 27 columns]

In [0]:
  #split training set
    df_train = dfHR[dfHR.Year<2018]
    df_test = dfHR[dfHR.Year==2018]

  #partition features
    X_train = df_train.drop(columns=['homicides', 'State', 'Year', 'HRExists', 'homicidespercap'])
    y_train = df_train.homicides

    # Partition the testing data into features and target
    X_test = df_test.drop(columns=['homicides', 'State', 'Year', 'HRExists', 'homicidespercap'])
    y_test = df_test.homicides

    # Initialize the model
    mdlhr = RandomForestRegressor()
    
    # Fit and train model
    train_score, test_score = fit_and_score_model(mdlhr, X_train, X_test, y_train, y_test)

the accuracy on the:
	 training data is 0.997
	 testing data is 0.976

/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)

# Magazine Ban

In [0]:
dfMag = pd.read_csv('https://docs.google.com/spreadsheets/d/e/2PACX-1vRrC0pd9TVoYAjBYG2OrrC0yO7VsOb-kvq3w0A8sN02JxbWw0PtEgWEnZckAWZqItE3fl51MzxsQpkU/pub?gid=1751727221&single=true&output=csv')
#normalize to log norm
dfMag.homicides = np.log(dfMag.homicides)
dfMag.head()

   Year       State  ...  AlcoholConsumptionPerCapita  PropOfMales
0  2014     Alabama  ...                         2.00     0.495271
1  2014      Alaska  ...                         2.79     0.535216
2  2014     Arizona  ...                         2.38     0.512376
3  2014    Arkansas  ...                         1.79     0.502776
4  2014  California  ...                         2.32     0.509981

[5 rows x 19 columns]

In [0]:
  #split training set
    df_train = dfMag[dfMag.Year<2018]
    df_test = dfMag[dfMag.Year==2018]

  #partition features
    X_train = df_train.drop(columns=['homicides', 'State', 'Year', 'MagExists', 'homicidespercap'])
    y_train = df_train.homicides

    # Partition the testing data into features and target
    X_test = df_test.drop(columns=['homicides', 'State', 'Year', 'MagExists', 'homicidespercap'])
    y_test = df_test.homicides

    # Initialize the model
    mdlmag = RandomForestRegressor()
    
    # Fit and train model
    train_score, test_score = fit_and_score_model(mdlmag, X_train, X_test, y_train, y_test)

the accuracy on the:
	 training data is 0.997
	 testing data is 0.976

/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)

# Stack - Can't stack if data sets are different

In [0]:
dfMag.head()

   Year       State  ...  AlcoholConsumptionPerCapita  PropOfMales
0  2014     Alabama  ...                         2.00     0.495271
1  2014      Alaska  ...                         2.79     0.535216
2  2014     Arizona  ...                         2.38     0.512376
3  2014    Arkansas  ...                         1.79     0.502776
4  2014  California  ...                         2.32     0.509981

[5 rows x 19 columns]

In [0]:
    #split training set
    df_trainStack = dfMag[dfMag.Year<2018]
    df_testStack = dfMag[dfMag.Year==2018]

  #partition features
    X_train = df_trainStack.drop(columns=['homicides', 'State', 'Year', 'MagExists', 'homicidespercap', 'magazine', 'tenroundlimit', 'magazinepreowned'])
    y_train = df_trainStack.homicides

    # Partition the testing data into features and target
    X_test = df_testStack.drop(columns=['homicides', 'State', 'Year', 'MagExists', 'homicidespercap', 'magazine', 'tenroundlimit', 'magazinepreowned'])
    y_test = df_testStack.homicides

In [0]:
def stack_models(X, models):
    # This function takes a dataset and a list of pre-trained models, and introduces
    # new features for each of the models.
    stack_features = pd.DataFrame(index=X.index)
    for i, mdl in enumerate(models):
        stack_features['mdl_{}'.format(i)] = mdl.predict(X)
    X = pd.concat([X, stack_features], axis=1)
    
    return X

# Define the set of best models
best_params_models = [mdlbg, mdlhr, mdlmag]

# Then stack
X_train1 = stack_models(X_train, best_params_models)
X_test1 = stack_models(X_test, best_params_models)

# We will use RF regressor
mdl_stack = RandomForestRegressor()

fit_and_score_model(mdl_stack,X_train1, X_test1, 
                                        y_train, 
                                        y_test)

ValueError: ignored